name: Job

on:
  push:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install

      - name: Run cypress tests
        run: npm run cypress:run

      - name: Generate cucumber HTML report
        run: |
          npm install -g cucumber-html-reporter
          cucumber-json-merge cypress/reports/cucumber/*.json > cypress/reports/cucumber/cucumber_report.json
          cucumber-html-reporter -o cypress/reports/cucumber/report.html -p cypress/reports/cucumber/cucumber_report.json

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: cypress-test-results
          path: |
            cypress/reports/cucumber/report.html  # Incluir el reporte HTML de Cucumber en los artefactos
