name: Job

on:
  push:
    branches:
      - main
      - dev

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install cypress and dependencies
        run: |
          npm install cypress
          npm install cypress-on-fix
          npm install mochawesome 
          npm install mochawesome-merge 
          npm install mochawesome-report-generator

      - name: Run cypress tests
        run: npm run cypress:run
        continue-on-error: true

      - name: Create directory for reports
        run: mkdir -p cypress/reports/mochawesome/
        continue-on-error: true

      - name: Merge cypress JSON report files
        run: npm run cypress:merge-reports-json
        continue-on-error: true

      - name: Generate HTML report
        run: npm run cypress:generate-html-report
        continue-on-error: true

      - name: Upload JSON report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressJSONReport
          path: /home/runner/work/mantishub-auto-cypress-cucumber/mantishub-auto-cypress-cucumber/cypress/reports/mochawesome/results.json
        continue-on-error: true

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressHTMLReport
          path: /home/runner/work/mantishub-auto-cypress-cucumber/mantishub-auto-cypress-cucumber/cypress/reports/mochawesome/results.html
        continue-on-error: true