name: job

on:
  push:
    branches: [main]

jobs:
  automation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Cypress and dependencies
        run: |
          npm install cypress @bahmutov/cypress-esbuild-preprocessor cypress-mochawesome-reporter mochawesome mochawesome-merge mochawesome-report-generator

      - name: Run Cypress tests and generate Mochawesome report
        run: |
          npx cypress run --reporter cypress-mochawesome-reporter --reporter-options reportDir=cypress/reports/mochawesome,overwrite=false,html=true
        continue-on-error: true

      - name: Create directory for reports
        run: mkdir -p cypress/reports/mochawesome
        continue-on-error: true
          
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressHTMLReport
          path: cypress/reports/mochawesome
        continue-on-error: true
