name: job

on:
  push:
    branches:
      - main
      - dev

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'

      - name: Install cypress and dependencies
        run: |
          npm install cypress @bahmutov/cypress-esbuild-preprocessor cypress-mochawesome-reporter mochawesome mochawesome-merge mochawesome-report-generator @badeball/cypress-cucumber-preprocessor

      - name: Create directory for reports
        run: mkdir -p cypress/reports/mochawesome

      - name: Run Cypress tests
        run: |
          npx cypress run --config-file /home/runner/work/mantishub-auto-cypress-cucumber/mantishub-auto-cypress-cucumber/cypress.config.js
        continue-on-error: true

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressHTMLReport
          path: /home/runner/work/mantisbt-auto/mantisbt-auto/cypress/reports/mochawesome
        continue-on-error: true
