name: job

on:
  push:
    branches: [main]

jobs:
  automation_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' 

      - name: Install Cypress and dependencies
        run: |
          npm install cypress
          npm install cypress-mochawesome-reporter mochawesome mochawesome-merge mochawesome-report-generator

      - name: Run Cypress tests and generate Mochawesome report
        run: |
          npm run cypress:run -- --reporter mochawesome --reporter-options reportDir=cypress/reports,overwrite=true,html=true
        continue-on-error: true
          
      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: CypressHTMLReport
          path: cypress/reports/report.html
        continue-on-error: true
